name: Swiftlint Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    allow-failure: true
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Run SwiftLint
      run: swiftlint